### ISSUE TITLE
Change tabs does not refresh all data

### ISSUE THREAD

**Issue by samoser** [oetiker/callbackery#25]
I have two tabs, both based on AbstractTable. Both have a SelectBox to select different data source.
![image](https://cloud.githubusercontent.com/assets/16583675/16420634/63d5686e-3d52-11e6-951d-6b82c78c9573.png)
When I change the tab, there is no way to remain SelectBox selection:
![image](https://cloud.githubusercontent.com/assets/16583675/16420683/95c19848-3d52-11e6-9c27-3830a3c2ce0d.png)
But even worse: after changing back, the SelectBox selection is lost, but data is still there:
![image](https://cloud.githubusercontent.com/assets/16583675/16420724/bdbf00ba-3d52-11e6-9b83-de48bf6f7307.png)
Imho, it should remain SelectBox selection or empty the table according to the 'empty' SelectBox selection.

**Comment by oetiker** [comment]
this is because on reload data the form gets supplied with current data from the backend ... if your GuiPlugin on the backend has no explicit `getData` method, then the backend will return `undef` values for every field field which will cause it the get emptied on reload ... a quick fix is to supply a `getAllFieldValues` method like this:

```perl
sub getAllFieldValues {
       return {}
```

**Comment by samoser** [comment]
Thanks mate. With this, the SelectBox selection persists :-) 
But table data is not refreshed. This is probably a different issue... ;-)
